name: awesome-lint

on:
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  lint:
    name: Run awesome-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install codespell
        run: python -m pip install --quiet "codespell==2.2.6"

      - name: Check English in docs and comments
        # Added EHR to the ignore-words-list below
        run: codespell -q 3 --skip=.git,node_modules --check-filenames --ignore-words-list="reworkd,EHR" .

      - name: Install dependencies
        run: npm install

      - name: Run awesome-lint
        run: npx awesome-lint
        env:
          CI: true
